import os
from datetime import datetime
from .utils import peso
TEMPLATE = """<!DOCTYPE html>
<html lang='en'><head><meta charset='utf-8'/><title>Invoice {{invoice_no}}</title>
<style>body{font-family:Arial,sans-serif;margin:32px;}h1{margin-bottom:0}.sub{color:#666;margin-top:2px}table{border-collapse:collapse;width:100%;margin-top:24px}th,td{border:1px solid #ddd;padding:8px;font-size:14px}th{background:#f5f5f5;text-align:left}.right{text-align:right}.totals td{font-weight:bold}.footer{margin-top:32px;color:#666;font-size:12px}</style>
</head><body>
<h1>INVOICE</h1>
<div class='sub'>Invoice No: {{invoice_no}}</div>
<div class='sub'>Billing Date: {{billing_date}}</div>
<h3>Bill To</h3>
<div>{{customer_name}}</div><div>{{customer_tin}}</div><div>{{business_address}}</div>
<table><thead><tr><th>#</th><th>Product</th><th class='right'>Qty</th><th class='right'>Unit Price</th><th class='right'>Discount</th><th class='right'>Line Total</th></tr></thead>
<tbody>{{rows_html}}</tbody>
<tfoot><tr class='totals'><td colspan='5' class='right'>Subtotal</td><td class='right'>{{subtotal}}</td></tr>
<tr class='totals'><td colspan='5' class='right'>VAT</td><td class='right'>{{vat}}</td></tr>
<tr class='totals'><td colspan='5' class='right'>Grand Total</td><td class='right'>{{grand_total}}</td></tr></tfoot></table>
<div class='footer'>Generated by TakeOut RMS on {{generated_at}}.</div></body></html>"""
def render_invoice_html(invoice_no,billing_date,customer_name,customer_tin,business_address,rows,subtotal,vat,grand_total):
    rows_html = ''
    for i,r in enumerate(rows, start=1):
        rows_html += (f"<tr><td>{i}</td><td>{r.get('product_name','')}</td><td class='right'>{r.get('quantity',0)}</td><td class='right'>{peso(r.get('item_price',0))}</td><td class='right'>{peso(r.get('discount',0))}</td><td class='right'>{peso(r.get('line_total',0))}</td></tr>")
    html = (TEMPLATE.replace("{{invoice_no}}", str(invoice_no)).replace("{{billing_date}}", str(billing_date)).replace("{{customer_name}}", customer_name or "").replace("{{customer_tin}}", customer_tin or "").replace("{{business_address}}", business_address or "").replace("{{rows_html}}", rows_html).replace("{{subtotal}}", peso(subtotal)).replace("{{vat}}", peso(vat)).replace("{{grand_total}}", peso(grand_total)).replace("{{generated_at}}", datetime.now().strftime('%Y-%m-%d %H:%M:%S')))
    return html
def save_invoice_html(path, html_str):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path,'w',encoding='utf-8') as f: f.write(html_str)
    return path
