[gdrive]
folder_id = "1m0fVLlUbp8NZ3oT1p8lwkixdnDfoJ-2v"

[gdrive_service_account]
type = "service_account"
project_id = "takeout-472205"
private_key_id = "ef3063dade21346ba62a5acf5039b08bf129e172"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCwzOmUl6TCsfY7
sXBLGFmajxPsRDQEs8roAmHxa5jBK+YvNGTCo1+8+kTRh3qUQ1p+I4ddgkOfJ+AV
xC6oUpCMSRSn6mNntIa3DZ+IN/sifvzgoxaaLQpvPHCkUc8b1T81Yb1J868QlcMO
VX52LuUEh3J8DftpYrHafVyEVowQP7FUDM2RXTP8zz/fnwy14oyKnCTMPx8RUDZf
JOgbKQw7hyVFd6T6Foy3A9XCWGOJ6Jk6aJfo0INBKloLOAO+bLzIJejek8cJD5VG
sX/a9e0lcIB5yVCCSkXurFN1cdZowme85+vx5q8rfi601MHHspwn79H9GluQ0z0q
e7aU79kFAgMBAAECggEAJ0Sb7KDxuzyDkCaM5mD2Jdn5dtR/KTw1qOo+jrxzJRR2
/60HZCOdM//yIQeSNjPveWyyuBYipsrYfn0gT8pmyIHC0LjCc1opQacI89xbLwI9
cDdI4d13H9Wwvw5cjbYDX/vhavdwvqJEvH5IpD8uJp9e0ibY3ENLdVe6oLoISeM9
Ike2tSBtEhVFWdg9WJdLz9aLTNcSEQRytfdNOywGv/TR58R00A4NX7R7LSWrg0tL
zL1BpV+PgWxhbFhAn2UoBkCdcW9xDRpdSyqgFyc3qLrt0ytMSjLBhQFB08CAqMbD
3YTKz4oU7vWPZsA7HPCjW7xt+kWBwTD+9DqTQv7+0QKBgQDVHFjARB8vyqUDMuJt
ZDoXjaNaEOOvaldnhtK0/DMN1PwERoofXuYe42nQWdKNxyHIKZzIt68ZX8pVtiSk
O8huQ2YQXIskyWam4nCaHXoMOtc8szg5u8BcU4x/iaGn7GJQZpRYSqKHRBc/hoBD
6QyiG9+bQjePmUrr6LzFP0tm8wKBgQDUYdPVE/5P2OvY73hT4+b9ev7tbLxTcNRN
OD3iCQ9tIVPfR46KYYXgvvTuhCeySboZdEBD7Mzos8p5qWUIAJsH5gfjckKOwJ6w
PxxUOieND7KLoqtEr+czQ/vCYvGFEB5NtkVcSGuLAeE6zPk3XAO/KI7z2dk6lBS7
QE/e4B6uJwKBgQCY2Vz6gaGQqJqT4cIvTYyw6gC4j5aOcQpBkZy8/IotqI4dDu7w
MyOAEgIJ0vLGh4W+R8JQ4BXxcBfyQ9KiDNLj6ulgYM/X0bATkCPNFck8zlMkETMJ
jZUZYz9JFlDg3RVir0BE1zsdI4Q9Jt4GVzedabqGZAbvsrXe4C3Ml2ogawKBgQCA
IOzdlgxNO789x2s+oTXQIw39SyZq6J0MYSvkXDb0TbD9+XujPKa6Kjo2U4BnbVda
1+mVkR0mHqG+uFV9eHAPWdXUgDBrUwXpqol6vwLxdVDwMRlGfSDsqs0OPwcakdjW
ZWp+/Cn1WRL6mIKZxWd1QhDMSNdnIcNIHMqS2X9o7QKBgQCRVSS7bd42bZwKocUy
AZZrM6UOPvrQPVcNqEfJvpoxqra1lqhtAdTfruKkdrsyAVG1O7cx/Rw49OME6RrJ
SeHDAIk+hltxN+u2Nk7lfHwV0lmukGu6dF7D4Z40/u9kSs6J7kSc3EmAge9858uu
1fut1Q0b4tV4/zGBVqpkOeav3Q==
-----END PRIVATE KEY-----"""
client_email = "takeout@takeout-472205.iam.gserviceaccount.com"
client_id = "118314496877913970183"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/takeout%40takeout-472205.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
